/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.58
 * Generated at: 2021-05-28 00:28:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import user.UserDAO;
import user.User;
import follow.FollowDAO;
import follow.Follow;
import java.io.PrintWriter;
import java.util.ArrayList;

public final class Search_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/navbar.jsp", Long.valueOf(1622161680029L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.io.PrintWriter");
    _jspx_imports_classes.add("user.User");
    _jspx_imports_classes.add("follow.Follow");
    _jspx_imports_classes.add("user.UserDAO");
    _jspx_imports_classes.add("follow.FollowDAO");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 request.setCharacterEncoding("UTF-8"); 
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>잔디공작소</title>\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"img/Contents_Logo.png\" type=\"img/x-icon\">\r\n");
      out.write("<link rel=\"icon\" href=\"img/Contents_Logo.png\" type=\"img/x-icon\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<style> \r\n");
      out.write("#undershadow{\r\n");
      out.write("\tbox-shadow: 0 3px 3px -3px rgba(0,0,0,0.10), 0 6px 6px -6px rgba(0,0,0,0.12), 0 6px 6px -6px rgba(0,0,0,0.14);\r\n");
      out.write("\tborder-radius: 0px;\r\n");
      out.write("}\r\n");
      out.write(".nav.navbar-form{\r\n");
      out.write("\tpadding: 0px 0px;\r\n");
      out.write("}\r\n");
      out.write(".navbar-header{\r\n");
      out.write("\tmargin: 0px;\r\n");
      out.write("\tpadding: 0px 0px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#logo{\r\n");
      out.write("\tfloat:left;\r\n");
      out.write("\twidth: 70%;\r\n");
      out.write("}\r\n");
      out.write("@font-face {\r\n");
      out.write("\tfont-family: 'regular';\r\n");
      out.write("    src: url('./fonts/NotoSansCJKkr-Regular.otf');\r\n");
      out.write("    font-weight: normal;\r\n");
      out.write("    font-style: normal;\r\n");
      out.write("}\r\n");
      out.write("#wich{\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\tmargin-left:8%;\r\n");
      out.write("}\r\n");
      out.write("#iconstyle{\r\n");
      out.write("\tborder: none;\r\n");
      out.write("\tbackground-color:#3dab4a;\r\n");
      out.write("\tcolor:white;\r\n");
      out.write("\tborder-top-left-radius: 7px;\r\n");
      out.write("\tborder-bottom-left-radius: 7px;\r\n");
      out.write("\tborder-right: 2px solid #ffffff;\t\r\n");
      out.write("}\r\n");
      out.write("#inputstyle{\r\n");
      out.write("\tfont-family: 'regular';\r\n");
      out.write("\tborder: none;\r\n");
      out.write("\tbackground-color:#3dab4a;\t\r\n");
      out.write("\tborder-top-right-radius: 7px;\r\n");
      out.write("\tborder-bottom-right-radius: 7px;\r\n");
      out.write("\tcolor:white;\r\n");
      out.write("\tline-height:100%;\r\n");
      out.write("  \tfont-size: 11pt;\r\n");
      out.write("}\r\n");
      out.write("#inputstyle::placeholder {\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\tfont-size: 11pt;\r\n");
      out.write("}\r\n");
      out.write("#inputstyle:focus{\r\n");
      out.write("\toutline: 0;\r\n");
      out.write("\t-webkit-box-shadow: none;\r\n");
      out.write("\tbox-shadow: none;\r\n");
      out.write("}\r\n");
      out.write("#up{\r\n");
      out.write("\tfloat: right;\r\n");
      out.write("}\r\n");
      out.write("#write{\r\n");
      out.write("\tpadding: 0;\r\n");
      out.write("\tbackground-color: #ffffff;\r\n");
      out.write("}\r\n");
      out.write("#repo{\r\n");
      out.write("\tpadding: 0;\r\n");
      out.write("\tbackground-color: #ffffff;\r\n");
      out.write("}\r\n");
      out.write("#user{\r\n");
      out.write("\tpadding: 0;\t\r\n");
      out.write("\tbackground-color: #ffffff;\r\n");
      out.write("}\r\n");
      out.write("#writei{\r\n");
      out.write("\twidth: 80%;\r\n");
      out.write("\theght: 80%;\r\n");
      out.write("}\r\n");
      out.write("#repoi{\r\n");
      out.write("\twidth: 80%;\r\n");
      out.write("\theght: 80%;\r\n");
      out.write("}\r\n");
      out.write("#useri{\r\n");
      out.write("\twidth: 80%;\r\n");
      out.write("\theght: 80%;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<nav class=\"navbar\" id=\"undershadow\">\r\n");
      out.write("  <div class=\"container\">\r\n");
      out.write("  \t<div class=\"row\">\r\n");
      out.write("  \t\t<div class=\"col-md-8 col-md-offset-2\" style=\"max-width:100%;\">  \t\t\t\r\n");
      out.write("    \t\t<form class=\"nav navbar-form\" role=\"search\" action=\"Search.jsp\">  \r\n");
      out.write("    \t\t<div class=\"navbar-header\">\r\n");
      out.write("        \t\t<a href=\"Main.jsp\"><img src=\"img/Header_Logo.png\" id=\"logo\" alt=\"로고 : Header_Logo\" ></a>\r\n");
      out.write("    \t\t</div>\r\n");
      out.write("  \t\t\t<div class=\"form-group\" id=\"wich\">\r\n");
      out.write("  \t\t    \t<div class=\"input-group\">\r\n");
      out.write("  \t\t\t\t\t<span class=\"input-group-addon\" id=\"iconstyle\"><i class=\"glyphicon glyphicon-search\"></i></span>\r\n");
      out.write("  \t\t\t\t\t<input type=\"text\" id=\"inputstyle\" class=\"form-control\" name=\"search\" placeholder=\"검색\" required=\"required\">\r\n");
      out.write("\t\t\t\t</div>         \t\t\r\n");
      out.write("        \t</div>       \t\r\n");
      out.write("\t        <ul id=\"up\" class=\"nav navbar-nav\">\t \r\n");
      out.write("\t    \t\t<li><a id=\"write\" href=\"Write.jsp\"><img id=\"writei\" src=\"img/Header_plus.png\"></a></li>\r\n");
      out.write("\t    \t\t<li><a id=\"repo\" href=\"Repo.jsp\"><img id=\"repoi\" src=\"img/Header_repo.png\"></a></li>\r\n");
      out.write("\t    \t\t<li><a id=\"user\" href=\"User.jsp\"><img id=\"useri\" src=\"img/Header_profile.png\"></a></li>\t   \t\t\r\n");
      out.write("\t        </ul>\r\n");
      out.write("      \t\t</form>\t\r\n");
      out.write("  \t\t</div>\r\n");
      out.write("  \t</div>\r\n");
      out.write("  </div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write('\r');
      out.write('\n');
      user.User user = null;
      user = (user.User) _jspx_page_context.getAttribute("user", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (user == null){
        user = new user.User();
        _jspx_page_context.setAttribute("user", user, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.introspecthelper(_jspx_page_context.findAttribute("user"), "userName", request.getParameter("userName"), request, "userName", false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/bootstrap.min.css\">\r\n");
      out.write("<title>잔디공작소</title>\r\n");
      out.write("<style>\r\n");
      out.write("  \t\tbody{ \r\n");
      out.write("  \t\t\tpadding-top: 90px; \r\n");
      out.write("  \t\t\tbackground-color: white;\r\n");
      out.write("  \t\t}\r\n");
      out.write("      \t.navbar-fixed-top{\r\n");
      out.write("      \t\tbackground-color: white;\r\n");
      out.write("      \t}\r\n");
      out.write("      \tbody{\r\n");
      out.write("      \tbackground-color: white;\r\n");
      out.write("      \t}\r\n");
      out.write("      \th1, #ps{\r\n");
      out.write("        \tfont-family: 'ImcreSoojin';\r\n");
      out.write("        }\r\n");
      out.write("        @font-face {\r\n");
      out.write("            font-family: 'ImcreSoojin';\r\n");
      out.write("            src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_20-04@2.3/ImcreSoojin.woff') format('woff');\r\n");
      out.write("            font-weight: normal;\r\n");
      out.write("            font-style: normal;\r\n");
      out.write("        }.pr-12 {\r\n");
      out.write("    padding-right: 12px !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".mb-20 {\r\n");
      out.write("    margin-bottom: 20px !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".b-1 {\r\n");
      out.write("    border: 1px solid #ebebeb !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card {\r\n");
      out.write("    border: 0;\r\n");
      out.write("    border-radius: 0;\r\n");
      out.write("    margin-bottom: 30px;\r\n");
      out.write("    -webkit-transition: .5s;\r\n");
      out.write("    transition: .5s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card {\r\n");
      out.write("    position: relative;\r\n");
      out.write("    display: -ms-flexbox;\r\n");
      out.write("    display: flex;\r\n");
      out.write("    -ms-flex-direction: column;\r\n");
      out.write("    flex-direction: column;\r\n");
      out.write("    min-width: 0;\r\n");
      out.write("    word-wrap: break-word;\r\n");
      out.write("    background-color: #fff;\r\n");
      out.write("    background-clip: border-box;\r\n");
      out.write("    border: 1px solid rgba(0,0,0,.125);\r\n");
      out.write("    border-radius: .25rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".media {\r\n");
      out.write("    padding: 16px 12px;\r\n");
      out.write("    -webkit-transition: background-color .2s linear;\r\n");
      out.write("    transition: background-color .2s linear;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".media {\r\n");
      out.write("    display: -ms-flexbox;\r\n");
      out.write("    display: flex;\r\n");
      out.write("    -ms-flex-align: start;\r\n");
      out.write("    align-items: flex-start;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card-body {\r\n");
      out.write("    -ms-flex: 1 1 auto;\r\n");
      out.write("    flex: 1 1 auto;\r\n");
      out.write("    padding: 1.25rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".media .avatar {\r\n");
      out.write("    flex-shrink: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".no-radius {\r\n");
      out.write("    border-radius: 0 !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".avatar-xl {\r\n");
      out.write("    width: 64px;\r\n");
      out.write("    height: 64px;\r\n");
      out.write("    line-height: 64px;\r\n");
      out.write("    font-size: 1.25rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".avatar {\r\n");
      out.write("    position: relative;\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    width: 36px;\r\n");
      out.write("    height: 36px;\r\n");
      out.write("    line-height: 36px;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    border-radius: 100%;\r\n");
      out.write("    background-color: #f5f6f7;\r\n");
      out.write("    color: #8b95a5;\r\n");
      out.write("    text-transform: uppercase;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("img {\r\n");
      out.write("    max-width: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("img {\r\n");
      out.write("    vertical-align: middle;\r\n");
      out.write("    border-style: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".mb-2 {\r\n");
      out.write("    margin-bottom: .5rem!important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".fs-20 {\r\n");
      out.write("    font-size: 20px !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".pr-16 {\r\n");
      out.write("    padding-right: 16px !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".ls-1 {\r\n");
      out.write("    letter-spacing: 1px !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".fw-300 {\r\n");
      out.write("    font-weight: 300 !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".fs-16 {\r\n");
      out.write("    font-size: 16px !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".media-body>* {\r\n");
      out.write("    margin-bottom: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("small, time, .small {\r\n");
      out.write("    font-family: Roboto,sans-serif;\r\n");
      out.write("    font-weight: 400;\r\n");
      out.write("    font-size: 11px;\r\n");
      out.write("    color: #8b95a5;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".fs-14 {\r\n");
      out.write("    font-size: 14px !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".mb-12 {\r\n");
      out.write("    margin-bottom: 12px !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".text-fade {\r\n");
      out.write("    color: rgba(77,82,89,0.7) !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card-footer:last-child {\r\n");
      out.write("    border-radius: 0 0 calc(.25rem - 1px) calc(.25rem - 1px);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card-footer {\r\n");
      out.write("    background-color: #fcfdfe;\r\n");
      out.write("    border-top: 1px solid rgba(77,82,89,0.07);\r\n");
      out.write("    color: #8b95a5;\r\n");
      out.write("    padding: 10px 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".flexbox {\r\n");
      out.write("    display: -webkit-box;\r\n");
      out.write("    display: flex;\r\n");
      out.write("    -webkit-box-pack: justify;\r\n");
      out.write("    justify-content: space-between;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".align-items-center {\r\n");
      out.write("    -ms-flex-align: center!important;\r\n");
      out.write("    align-items: center!important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card-footer {\r\n");
      out.write("    padding: .75rem 1.25rem;\r\n");
      out.write("    background-color: rgba(0,0,0,.03);\r\n");
      out.write("    border-top: 1px solid rgba(0,0,0,.125);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".card-footer {\r\n");
      out.write("    background-color: #fcfdfe;\r\n");
      out.write("    border-top: 1px solid rgba(77, 82, 89, 0.07);\r\n");
      out.write("    color: #8b95a5;\r\n");
      out.write("    padding: 10px 20px\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card-footer>*:last-child {\r\n");
      out.write("    margin-bottom: 0\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".hover-shadow {\r\n");
      out.write("    -webkit-box-shadow: 0 0 35px rgba(0, 0, 0, 0.11);\r\n");
      out.write("    box-shadow: 0 0 35px rgba(0, 0, 0, 0.11)\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".fs-10 {\r\n");
      out.write("    font-size: 10px !important;\r\n");
      out.write("}\r\n");
      out.write("\t\r\n");
      out.write("        \r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    \r\n");
      out.write("  \t");

  	String username = request.getParameter("userName");
 	UserDAO userDAO=new UserDAO();
 	FollowDAO followDAO=new FollowDAO();
	ArrayList<User> list=userDAO.search(username);
	for(int i=0; i<list.size(); i++){
	int follow=followDAO.SearchFollowing(userID,list.get(i).getUserID()); 

	
      out.write("\r\n");
      out.write("\t\r\n");
      out.write(" \t<p class=\"card-text\"></p>\r\n");
      out.write(" \t<div class=\"container\">\r\n");
      out.write("\t\t<div class=\"col-md-12\">\r\n");
      out.write("    \t\t<div class=\"card b-1 hover-shadow mb-20\">\r\n");
      out.write("        \t\t<div class=\"media card-body\"> \r\n");
      out.write("           \t\t\t<div class=\"media-body\">\r\n");
      out.write("           \t\t\t\t<form method=\"post\" action=\"Follow.jsp\">\r\n");
      out.write("                \t\t\t<div class=\"mb-2\">\r\n");
      out.write("                \t\t\t\t<span style=\"cursor:pointer;\"class=\"fs-20 pr-16\" onclick=\"location.href='SearchUser.jsp?id=");
      out.print(list.get(i).getUserID());
      out.write("'\" >");
      out.print(list.get(i).getUserName() );
      out.write("</span>\r\n");
      out.write("               \t\t\t\t</div>\r\n");
      out.write("               \t\t\t@");
      out.print(list.get(i).getUserID());
      out.write("</input><br>\r\n");
      out.write("               \t\t\t\r\n");
      out.write("                \t\t<p class=\"fs-14 text-fade mb-12\"><i class=\"fa fa-map-marker pr-1\"></i>");
      out.print(list.get(i).getUserEmail());
      out.write("</p>\r\n");
      out.write("                \t\t\r\n");
      out.write("            \t\t</div>\r\n");
      out.write("        \t\t</div>\r\n");
      out.write("        \t\t<footer class=\"card-footer flexbox align-items-center\">\r\n");
      out.write("            \t<div>\r\n");
      out.write("               \t\t<strong>Join on:</strong>\r\n");
      out.write("               \t\t<span>");
      out.print( list.get(i).getUserDate().substring(0, 16) );
      out.write("</span>             \r\n");
      out.write("               \t\t\r\n");
      out.write("            \t</div>\r\n");
      out.write("            \t<div class=\"media-right text-right d-none d-md-block\">\r\n");
      out.write("            \t<input type=\"text\" name=\"id\" style=\"display:none\" value=");
      out.print(list.get(i).getUserID());
      out.write(">\r\n");
      out.write("            \t\t");
 if(list.get(i).getUserID().equals(userID)){
      out.write("\r\n");
      out.write("                \t");
  }else if(follow>0){
      out.write("\r\n");
      out.write("                \t<a href='Unfollow.jsp?id=");
      out.print(list.get(i).getUserID());
      out.write("' class=\"btn btn-success\" value=\"UNFOLLOW\">UNFOLLOW</a>\r\n");
      out.write("                \t");
}else{
      out.write("\r\n");
      out.write("                \t<a href='Follow.jsp?id=");
      out.print(list.get(i).getUserID());
      out.write("' class=\"btn btn-success\" value=\"FOLLOW\">FOLLOW</a>\r\n");
      out.write("                \t");
} 
      out.write("\r\n");
      out.write("            \t</div>\r\n");
      out.write("        \t\t</footer>\r\n");
      out.write("        \t\t</form>\r\n");
      out.write("    \t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write(" \t");
user.setUserID(list.get(i).getUserID());
      out.write("\r\n");
      out.write(" \t");
}
      out.write("\r\n");
      out.write("\r\n");
      out.write("  </body>\r\n");
      out.write(" </html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
