/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.58
 * Generated at: 2021-06-18 01:40:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.text.Format;
import user.UserDAO;
import user.User;
import bbs.BbsDAO;
import bbs.Bbs;
import follow.FollowDAO;
import follow.Follow;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import java.text.SimpleDateFormat;

public final class User_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("bbs.Bbs");
    _jspx_imports_classes.add("java.io.PrintWriter");
    _jspx_imports_classes.add("user.User");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.text.Format");
    _jspx_imports_classes.add("java.util.Calendar");
    _jspx_imports_classes.add("bbs.BbsDAO");
    _jspx_imports_classes.add("follow.Follow");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
    _jspx_imports_classes.add("user.UserDAO");
    _jspx_imports_classes.add("follow.FollowDAO");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>잔디공작소</title>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/User.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/navbar.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css\">\r\n");
      out.write("<link href=\"https://www.jqueryscript.net/css/jquerysctipttop.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"dist/jquery.calmosaic.min.css\">\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"img/Contents_Logo.png\" type=\"img/x-icon\">\r\n");
      out.write("<link rel=\"icon\" href=\"img/Contents_Logo.png\" type=\"img/x-icon\">\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.3.1/dist/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/moment@2.24.0/moment.min.js\"></script>\r\n");
      out.write("<script src=\"dist/jquery.calmosaic.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\t\r\n");
      out.write("<nav class=\"navbar\" id=\"undershadow\">\r\n");
      out.write("  <div class=\"container\">\r\n");
      out.write("  \t<div class=\"row\">\r\n");
      out.write("  \t\t<div class=\"col-md-8 col-md-offset-2\" style=\"max-width:100%;\">  \t\t\t\r\n");
      out.write("    \t\t<form class=\"nav navbar-form\" role=\"search\" action=\"Search.jsp\">  \r\n");
      out.write("    \t\t<div class=\"navbar-header\">\r\n");
      out.write("        \t\t<a href=\"Main.jsp\"><img src=\"img/Header_Log.png\" id=\"logo\" alt=\"로고 : Header_Logo\" ></a>\r\n");
      out.write("    \t\t</div>\r\n");
      out.write("  \t\t\t<div class=\"form-group\" id=\"wich\">\r\n");
      out.write("  \t\t    \t<div class=\"input-group\">\r\n");
      out.write("  \t\t\t\t\t<span class=\"input-group-addon\" id=\"iconstyle\"><i class=\"glyphicon glyphicon-search\"></i></span>\r\n");
      out.write("  \t\t\t\t\t<input type=\"text\" id=\"inputstyle\" class=\"form-control\" name=\"search\" placeholder=\"검색\" required=\"required\">\r\n");
      out.write("\t\t\t\t</div>         \t\t\r\n");
      out.write("        \t</div>\r\n");
      out.write("\t    \t\t<a id=\"user\" href=\"User.jsp\" style=\"pointer-events: none;\"><img id=\"useri\" src=\"img/Profile_Green.png\"></a>\r\n");
      out.write("\t    \t\t<a id=\"write\" href=\"Write.jsp\"><img id=\"writei\" src=\"img/Header_plu.png\"></a>        \r\n");
      out.write("      \t\t</form>\t\r\n");
      out.write("  \t\t</div>\r\n");
      out.write("  \t</div>\r\n");
      out.write("  </div>\r\n");
      out.write("</nav>\r\n");
 
String userID = (String)session.getAttribute("userID");
Calendar cal = Calendar.getInstance();
UserDAO userDAO = new UserDAO();
BbsDAO bbsDAO = new BbsDAO();
ArrayList<User> user = userDAO.user(userID);
FollowDAO followDAO = new FollowDAO();
int monthcount = bbsDAO.getmonthCount(userID, String.valueOf((cal.get(Calendar.MONTH)+1)));
String imgurl="./upload/"+user.get(0).getUserPicture();
System.out.print(imgurl);

      out.write("\t\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("  <div class=\"row\">     \r\n");
      out.write("    <div class=\"col-md-10 col-md-offset-1\" style=\"max-width:100%;\"> \r\n");
      out.write("    \r\n");
      out.write("    <div class=\"col-md-3\" id=\"box1\"> \r\n");
      out.write("\t  <div class=\"card\">\r\n");
      out.write("\t  \t<img class=\"card-img-top\" id=\"img_click\" src=\"./img/");
      out.print(user.get(0).getUserPicture());
      out.write("\">\t  \t\r\n");
      out.write("   \t\t<div class=\"card-body\">\r\n");
      out.write("  \t\t\t<h4 class=\"card-title\" id=\"userid\">");
      out.print(userID);
      out.write("</h4>\r\n");
      out.write("  \t\t\t<a href=\"ModifyUser.jsp\" id=\"modifyuser\">프로필 편집</a>\r\n");
      out.write("  \t\t\t<p class=\"card-text\" id=\"username\">");
      out.print(user.get(0).getUserName());
      out.write("</p> \t\r\n");
      out.write("  \t\t\t\r\n");
      out.write("  \t\t\t<img src=\"img/follow_icon.png\" width=\"25\" height=\"25\" style=\"float:left;\">\r\n");
      out.write("  \t\t\t<a href=\"GetFollowList.jsp\">\r\n");
      out.write("  \t\t\t\r\n");
      out.write("  \t\t\t  <p id=\"follow\">&nbsp;팔로워</p>\r\n");
      out.write("  \t\t\t  <p id=\"follownum\">");
      out.print(followDAO.getFollowing(userID));
      out.write("</p>\r\n");
      out.write("  \t\t\t</a>\r\n");
      out.write("  \t\t\t<a href=\"GetFollowingList.jsp\">\r\n");
      out.write("  \t\t\t  <p id=\"follow\">&nbsp;&nbsp;팔로잉</p>\r\n");
      out.write("  \t\t\t  <p id=\"follownum\">");
      out.print(followDAO.getFollow(userID));
      out.write("</p>\r\n");
      out.write("  \t\t\t</a>\r\n");
      out.write("  \t\t\t<span id=\"email\" class=\"glyphicon glyphicon-envelope\" aria-hidden=\"true\">&nbsp;");
      out.print(user.get(0).getUserEmail());
      out.write("</span>\r\n");
      out.write("  \t\t\t  \t\t\t\r\n");
      out.write("  \t\t</div>\t\r\n");
      out.write("  \t  </div>\r\n");
      out.write("  \t</div>\r\n");
      out.write("  \t  <!-- pointer-events: none; 링크 비활성화  -->\r\n");
      out.write("  \t \r\n");
      out.write("  \t<div class=\"col-md-9\" id=\"box2\"> \r\n");
      out.write("  \t\r\n");
      out.write("  \t<a href=\"User.jsp\" id=\"overview\"><img src=\"img/overview.png\" width=\"25\" height=\"25\" />&nbsp;Overview</a>\r\n");
      out.write("  \t<a href=\"Repo.jsp\" id=\"user_nav\"><img src=\"img/Repositories.png\" width=\"25\" height=\"25\" />&nbsp;Repositories</a>\r\n");
      out.write("  \t<a href=\"#\" id=\"user_nav\"><img src=\"img/setting.png\" width=\"25\" height=\"25\" />&nbsp;Settings</a><br>\r\n");
      out.write("  \t<hr id=\"navlow\">\r\n");
      out.write("  \t\r\n");
      out.write("  \t");

    ArrayList<Bbs> getrepo= bbsDAO.getrepo(userID);
    for(int i=0; i<9; i++){
      if(getrepo.size()==i)
        break;
	
      out.write("\t\t\t\r\n");
      out.write("\t<div id=\"repo_box\">\r\n");
      out.write("\t  <a id=\"repobbstitle\" style=\"font-size:18px;\"href=\"Show.jsp?bbsID=");
      out.print(getrepo.get(i).getBbsID());
      out.write('"');
      out.write('>');
      out.print(getrepo.get(i).getBbsTitle());
      out.write("</a><br>\r\n");
      out.write("\t  <p id=\"lang\">");
      out.print(getrepo.get(i).getBbsLanguage() );
      out.write("</p>\r\n");
      out.write("\t</div>\r\n");
      out.write("     ");

     }
     
      out.write(" \r\n");
      out.write("  \t  \r\n");
      out.write("  \t</div>\r\n");
      out.write("  \t\r\n");
      out.write("  \t</div>\r\n");
      out.write("  \t<div id=\"heatmap-1\"></div>  \r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("  \t\t\t \t <div class=\"modal\" id=\"myModal\" tabindex=\"-1\">\r\n");
      out.write("  \t\t\t\t \t<div class=\"modal-dialog\">\r\n");
      out.write("    \t\t\t\t\t<div class=\"modal-content\">\r\n");
      out.write("    \t\t\t\t\t    <div class=\"modal-header\">\r\n");
      out.write("    \t\t\t\t\t    \t<h5 class=\"modal-title\">Profile Modify</h5>\r\n");
      out.write("        \t\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("          \t\t\t\t\t\t\t<span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("        \t\t\t\t\t\t</button>\r\n");
      out.write("      \t\t\t\t\t\t</div>\r\n");
      out.write("  \t\t\t\t\t\t\t<div class=\"modal-body\">\r\n");
      out.write("\t  \t\t\t\t\t\t\t<h5>프로필 사진 수정하기</h5>\r\n");
      out.write("\t  \t\t\t\t\t\t\t<form method=\"post\" enctype=\"multipart/form-data\" action=\"Upload.jsp\">\r\n");
      out.write("\t  \t\t\t\t\t\t\t\t<input type=\"file\" name=\"file\" id=\"bfile\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"submit\" value=\"업로드\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t\t<script>\r\n");
      out.write("\t    \t\t\t\t\t\t\tvar fileCheck = document.getElementById(\"bfile\").value;\r\n");
      out.write("\t    \t\t\t\t\t\t\tif(!fileCheck){\r\n");
      out.write("\t        \t\t\t\t\t\t\talert(\"파일을 첨부해 주세요\");\r\n");
      out.write("\t        \t\t\t\t\t\t\treturn false;\r\n");
      out.write("\t    \t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t</script>\r\n");
      out.write("\t  \t\t\t\t\t\t\t<hr>\r\n");
      out.write("\t  \t\t\t\t\t\t\t<button type=\"button\" name=\"basicimg\" class=\"btn btn-success btn-lg btn-block\" onclick=\"location.href='BasicPictureUpload.jsp'\">기본 이미지로 변경하기</button>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("    \t\t\t\t</div>\r\n");
      out.write("  \t\t\t\t</div>\r\n");
      out.write("  \t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("        \t\t\r\n");
      out.write("        \t\t\r\n");
      out.write("        \t\t\r\n");
      out.write("\r\n");
      out.write("     \r\n");
      out.write("      \t\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("var data=[];    \r\n");
 
	int count = bbsDAO.getCount(userID);
	List<String> date=bbsDAO.getalldate(userID);
	System.out.println(count);
	for (int i = 0; i <count; i++) {
		System.out.println(date.get(i).substring(0, 10).toString());
      out.write("\r\n");
      out.write("\t\tdata.push({count:2, date:\"");
      out.print(date.get(i).substring(0, 10).toString());
      out.write("\"});      \r\n");
      out.write("\t");

	}

      out.write("\r\n");
      out.write("    $(\"#heatmap-1\").calmosaic(data, {\r\n");
      out.write("        lastMonth: moment().month()+1,\r\n");
      out.write("        coloring: \"\",\r\n");
      out.write("        legend: {\r\n");
      out.write("            minLabel: \"Fewer\"\r\n");
      out.write("        },\r\n");
      out.write("        labels: {\r\n");
      out.write("            custom: {\r\n");
      out.write("                monthLabels: \"MMM\"\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write(" \r\n");
      out.write("\t\r\n");
      out.write("var modal = document.getElementById('myModal');\r\n");
      out.write("// Get the button that opens the modal\r\n");
      out.write("var btn = document.getElementById(\"img_click\");\r\n");
      out.write("// Get the <span> element that closes the modal\r\n");
      out.write("var span = document.getElementsByClassName(\"close\")[0];                                          \r\n");
      out.write("// When the user clicks on the button, open the modal \r\n");
      out.write("btn.onclick = function() {\r\n");
      out.write("\tmodal.style.display = \"block\";\r\n");
      out.write("}\r\n");
      out.write("// When the user clicks on <span> (x), close the modal\r\n");
      out.write("span.onclick = function() {\r\n");
      out.write("\tmodal.style.display = \"none\";\r\n");
      out.write("}\r\n");
      out.write("// When the user clicks anywhere outside of the modal, close it\r\n");
      out.write("window.onclick = function(event) {\r\n");
      out.write("\tif (event.target == modal) \r\n");
      out.write("    \tmodal.style.display = \"none\";\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
