/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.58
 * Generated at: 2020-10-06 16:25:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.try_;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Boot_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css\" integrity=\"sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z\" crossorigin=\"anonymous\">\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.5.1.slim.min.js\" integrity=\"sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\" integrity=\"sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js\" integrity=\"sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<title>부트스트랩 적용하기 연습</title>\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"flex-grow-1 d-flex flex-column\">\r\n");
      out.write("    <nav class=\"navbar navbar-expand-md navbar-light bg-light navbar-expand-md\">\r\n");
      out.write("        <a class=\"navbar-brand\" href=\"#\">Navbar</a>\r\n");
      out.write("        <ul class=\"navbar-nav w-100\">\r\n");
      out.write("            <li class=\"nav-item\"><a href=\"#\" class=\"nav-link\">Home</a></li>\r\n");
      out.write("            <li class=\"nav-item\"><a href=\"#\" class=\"nav-link\">Link</a></li>\r\n");
      out.write("            <li class=\"nav-item\"><a href=\"#\" class=\"nav-link\">Link</a></li>\r\n");
      out.write("            <li class=\"nav-item ml-md-auto\"><a href=\"https://themestr.app/\" class=\"nav-link\">Themestr.app</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </nav>\r\n");
      out.write("    <!-- /bootstrap nav -->\r\n");
      out.write("    <div class=\"container-fluid\">\r\n");
      out.write("        <!-- bootstrap nav -->\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div class=\"col-xl-9 col-lg-10 mx-auto\" id=\"content\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-md pt-5\">\r\n");
      out.write("                        <section id=\"buttons\" class=\"pb-2\">\r\n");
      out.write("                            <div class=\"row\">\r\n");
      out.write("                                <div class=\"col-12\">\r\n");
      out.write("\r\n");
      out.write("                                    <!-- Breadcrumb -->\r\n");
      out.write("                                    <nav aria-label=\"breadcrumb\">\r\n");
      out.write("                                        <ol class=\"breadcrumb\">\r\n");
      out.write("                                            <li class=\"breadcrumb-item\"><a href=\"#\">Home</a></li>\r\n");
      out.write("                                            <li class=\"breadcrumb-item\"><a href=\"#\">Library</a></li>\r\n");
      out.write("                                            <li class=\"breadcrumb-item active\" aria-current=\"page\">Breadcrumb</li>\r\n");
      out.write("                                        </ol>\r\n");
      out.write("                                    </nav>\r\n");
      out.write("\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"col-lg-4\">\r\n");
      out.write("                                    <div class=\"pb-3\">\r\n");
      out.write("                                        <button type=\"button\" class=\"btn btn-primary mr-1\">Button</button>\r\n");
      out.write("                                        <button type=\"button\" class=\"btn btn-outline-primary\">Outline</button>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"pb-3\">\r\n");
      out.write("                                        <!-- Large Button -->\r\n");
      out.write("                                        <button type=\"button\" class=\"btn btn-primary align-bottom btn-lg mr-1\">Large</button>\r\n");
      out.write("\r\n");
      out.write("                                        <!-- Small Button -->\r\n");
      out.write("                                        <button type=\"button\" class=\"btn btn-primary align-bottom btn-sm mr-1\">Small</button>\r\n");
      out.write("\r\n");
      out.write("                                        <!-- Link -->\r\n");
      out.write("                                        <a href=\"#\">Text</a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"col-lg-8 text-right\">\r\n");
      out.write("\r\n");
      out.write("                                    <!-- Button toolbar -->\r\n");
      out.write("                                    <div class=\"btn-toolbar d-inline-block mb-3\" role=\"toolbar\" aria-label=\"Toolbar with button groups\">\r\n");
      out.write("                                        <div class=\"btn-group mr-2\" role=\"group\" aria-label=\"First group\">\r\n");
      out.write("                                            <button type=\"button\" class=\"btn btn-outline-primary\">1</button>\r\n");
      out.write("                                            <button type=\"button\" class=\"btn btn-primary\">2</button>\r\n");
      out.write("                                            <button type=\"button\" class=\"btn btn-primary\">3</button>\r\n");
      out.write("                                            <button type=\"button\" class=\"btn btn-primary\">4</button>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"btn-group mr-2\" role=\"group\" aria-label=\"Second group\">\r\n");
      out.write("                                            <button type=\"button\" class=\"btn btn-primary\">5</button>\r\n");
      out.write("                                            <button type=\"button\" class=\"btn btn-primary\">6</button>\r\n");
      out.write("                                            <button type=\"button\" class=\"btn btn-primary\">7</button>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"btn-group\" role=\"group\" aria-label=\"Third group\">\r\n");
      out.write("                                            <button type=\"button\" class=\"btn btn-primary\">8</button>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                    <!-- Dropdown Button -->\r\n");
      out.write("                                    <div class=\"dropdown\">\r\n");
      out.write("                                        <button class=\"btn btn-primary dropdown-toggle\" type=\"button\" id=\"dropdownMenuButton\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("                                            Dropdown button\r\n");
      out.write("                                        </button>\r\n");
      out.write("                                        <div class=\"dropdown-menu\" aria-labelledby=\"dropdownMenuButton\">\r\n");
      out.write("                                            <a class=\"dropdown-item\" href=\"#\">Action</a>\r\n");
      out.write("                                            <a class=\"dropdown-item\" href=\"#\">Another action</a>\r\n");
      out.write("                                            <a class=\"dropdown-item\" href=\"#\">Something else here</a>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"col-12 py-4\">\r\n");
      out.write("                                    <button class=\"btn btn-primary mr-1 mb-1\">Primary</button>\r\n");
      out.write("                                    <button class=\"btn btn-secondary mr-1 mb-1\">Secondary</button>\r\n");
      out.write("                                    <button class=\"btn btn-info mr-1 mb-1\">Info</button>\r\n");
      out.write("                                    <button class=\"btn btn-danger mr-1 mb-1\">Danger</button>\r\n");
      out.write("                                    <button class=\"btn btn-success mr-1 mb-1\">Success</button>\r\n");
      out.write("                                    <button class=\"btn btn-warning mr-1 mb-1\">Warning</button>\r\n");
      out.write("                                    <button class=\"btn btn-light border mr-1 mb-1\">Light</button>\r\n");
      out.write("                                    <button class=\"btn btn-dark mr-1 mb-1\">Dark</button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </section>\r\n");
      out.write("\r\n");
      out.write("                        <section id=\"navs\" class=\"py-3\">\r\n");
      out.write("                            <div class=\"row\">\r\n");
      out.write("                                <div class=\"col-lg-9 pb-4\">\r\n");
      out.write("\r\n");
      out.write("                                    <!-- Nav -->\r\n");
      out.write("                                    <ul class=\"nav\">\r\n");
      out.write("                                        <li class=\"nav-item\">\r\n");
      out.write("                                            <a class=\"nav-link pl-0\" href=\"#\">Link</a>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li class=\"nav-item\">\r\n");
      out.write("                                            <a class=\"nav-link\" href=\"#\">Link</a>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li class=\"nav-item\">\r\n");
      out.write("                                            <a class=\"nav-link\" href=\"#\">Link</a>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li class=\"nav-item\">\r\n");
      out.write("                                            <a class=\"nav-link disabled\" href=\"#\">Disabled</a>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                    <hr>\r\n");
      out.write("\r\n");
      out.write("                                    <!-- Nav Tabs -->\r\n");
      out.write("                                    <ul class=\"nav nav-tabs\">\r\n");
      out.write("                                        <li class=\"nav-item\">\r\n");
      out.write("                                            <a class=\"nav-link active\" href=\"#tab1\" data-toggle=\"tab\">Tab</a>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li class=\"nav-item\">\r\n");
      out.write("                                            <a class=\"nav-link\" href=\"#tab2\" data-toggle=\"tab\">Tab</a>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li class=\"nav-item\">\r\n");
      out.write("                                            <a class=\"nav-link\" href=\"#tab3\" data-toggle=\"tab\">Tab</a>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li class=\"nav-item\">\r\n");
      out.write("                                            <a class=\"nav-link disabled\" href=\"#tab4\" data-toggle=\"tab\">Disabled</a>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                    <div class=\"tab-content px-1 pt-2\">\r\n");
      out.write("                                        <div class=\"tab-pane active\" id=\"tab1\">\r\n");
      out.write("                                            <p>\r\n");
      out.write("                                                Welcome to my custom Bootstrap 4 test page that is a simple way to see various Bootstrap component examples. Customize Bootstrap with <a href=\"https://themestr.app\">Themestr.app</a>.\r\n");
      out.write("                                            </p>\r\n");
      out.write("                                            <nav aria-label=\"Page navigation example\">\r\n");
      out.write("                                                <ul class=\"pagination\">\r\n");
      out.write("                                                    <li class=\"page-item\"><a class=\"page-link\" href=\"#\">Previous</a></li>\r\n");
      out.write("                                                    <li class=\"page-item\"><a class=\"page-link\" href=\"#\">1</a></li>\r\n");
      out.write("                                                    <li class=\"page-item\"><a class=\"page-link\" href=\"#\">2</a></li>\r\n");
      out.write("                                                    <li class=\"page-item\"><a class=\"page-link\" href=\"#\">3</a></li>\r\n");
      out.write("                                                    <li class=\"page-item\"><a class=\"page-link\" href=\"#\">Next</a></li>\r\n");
      out.write("                                                </ul>\r\n");
      out.write("                                            </nav>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"tab-pane\" id=\"tab2\">2. Put a little content in your pane.</div>\r\n");
      out.write("                                        <div class=\"tab-pane\" id=\"tab3\">3. Put some more content in your pane here.</div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"col-lg-3 pb-4\">\r\n");
      out.write("\r\n");
      out.write("                                    <!-- Vertical Nav -->\r\n");
      out.write("                                    <ul class=\"nav nav-pills flex-column mb-3\">\r\n");
      out.write("                                        <li class=\"nav-item\">\r\n");
      out.write("                                            <a class=\"nav-link active\" href=\"#\" data-toggle=\"popover\" data-trigger=\"hover\" data-placement=\"top\" data-title=\"Primary color\" data-content=\"Links and 'active' elements always use the primary color.\">Active</a>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li class=\"nav-item\">\r\n");
      out.write("                                            <a class=\"nav-link\" href=\"#\">Link</a>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li class=\"nav-item\">\r\n");
      out.write("                                            <a class=\"nav-link\" href=\"#\">Link</a>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li class=\"nav-item\">\r\n");
      out.write("                                            <a class=\"nav-link\" href=\"#\">Link</a>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                    <!-- Dropdown Split Button -->\r\n");
      out.write("                                    <div class=\"btn-group mb-3\">\r\n");
      out.write("                                        <button type=\"button\" class=\"btn btn-primary btn-block\">Split Dropdown</button>\r\n");
      out.write("                                        <button type=\"button\" class=\"btn btn-primary dropdown-toggle dropdown-toggle-split\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("                                            <span class=\"sr-only\">Toggle Dropdown</span>\r\n");
      out.write("                                        </button>\r\n");
      out.write("                                        <div class=\"dropdown-menu dropdown-menu-right\">\r\n");
      out.write("                                            <a class=\"dropdown-item\" href=\"#\">Action</a>\r\n");
      out.write("                                            <a class=\"dropdown-item\" href=\"#\">Link</a>\r\n");
      out.write("                                            <div class=\"dropdown-divider\"></div>\r\n");
      out.write("                                            <a class=\"dropdown-item\" href=\"#\">Separated link</a>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </section>\r\n");
      out.write("\r\n");
      out.write("                        <section id=\"cards\" class=\"bg-faded py-2\">\r\n");
      out.write("                            <div class=\"d-flex my-3\">\r\n");
      out.write("\r\n");
      out.write("                                <!-- Jumbotron -->\r\n");
      out.write("                                <div class=\"jumbotron w-100 py-5 mx-auto\">\r\n");
      out.write("                                    <h1 class=\"display-3\">Hello, world!</h1>\r\n");
      out.write("                                    <p class=\"lead\">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"row\">\r\n");
      out.write("                                <div class=\"col-xl-6 col-lg-4 mb-4\">\r\n");
      out.write("\r\n");
      out.write("                                    <!-- Card -->\r\n");
      out.write("                                    <div class=\"card border-primary h-100\">\r\n");
      out.write("                                        <div class=\"card-body d-flex flex-column align-items-start\">\r\n");
      out.write("                                            <h4 class=\"card-title text-primary\">Card Outline</h4>\r\n");
      out.write("                                            <p class=\"card-text\">With supporting text below as a natural lead-in to additional content. This has text that may wrap to the next line.</p>\r\n");
      out.write("                                            <a href=\"#\" class=\"btn btn-primary mt-auto\">Button</a>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"col-xl-6 col-lg-4 mb-4\">\r\n");
      out.write("                                    <div class=\"card border-primary h-100\">\r\n");
      out.write("                                        <div class=\"card-body\">\r\n");
      out.write("\r\n");
      out.write("                                            <!-- List Group -->\r\n");
      out.write("                                            <div class=\"list-group\">\r\n");
      out.write("                                                <a href=\"#\" class=\"list-group-item list-group-item-action active\">List Group</a>\r\n");
      out.write("                                                <a href=\"#\" class=\"list-group-item list-group-item-action\">List item</a>\r\n");
      out.write("                                                <a href=\"#\" class=\"list-group-item list-group-item-action\">List item 2</a>\r\n");
      out.write("                                                <a href=\"#\" class=\"list-group-item list-group-item-action disabled\">List item 3</a>\r\n");
      out.write("                                            </div>\r\n");
      out.write("\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"col-xl-12 col-lg-4 mb-4\">\r\n");
      out.write("                                    <div class=\"card bg-primary text-white h-100\">\r\n");
      out.write("                                        <div class=\"card-body d-flex flex-column align-items-start\">\r\n");
      out.write("                                            <h4 class=\"card-title\">Card</h4>\r\n");
      out.write("                                            <p class=\"card-text\">Watch me scale, scale. Now watch me stack, stack. Watch me scale, scale...</p>\r\n");
      out.write("                                            <a href=\"#\" class=\"btn btn-primary border-white mt-auto\">Button</a>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </section>\r\n");
      out.write("                        \r\n");
      out.write("                        <section>\r\n");
      out.write("                            <h1>Heading 1</h1>\r\n");
      out.write("                            <h2>Heading 2</h2>\r\n");
      out.write("                            <h3>Heading 3</h3>\r\n");
      out.write("                            <h4>Heading 4</h4>\r\n");
      out.write("                            <h5>Heading 5</h5>\r\n");
      out.write("                        </section>\r\n");
      out.write("\r\n");
      out.write("                        <section id=\"grid\" class=\"py-3\">\r\n");
      out.write("                            <p class=\"lead\">The rows &amp; columns of the world famous Bootstrap grid speak for themselves.</p>\r\n");
      out.write("                            <div class=\"row\">\r\n");
      out.write("                                <div class=\"col-sm-6\">\r\n");
      out.write("                                    6\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"col-6\">\r\n");
      out.write("                                    <div class=\"card my-1 bg-light\">6</div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"col-sm-5\">\r\n");
      out.write("                                    5\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"col-7\">\r\n");
      out.write("                                    <div class=\"card my-1\">7</div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"col-sm-4\">\r\n");
      out.write("                                    4\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"col-8\">\r\n");
      out.write("                                    <div class=\"card my-1\">8</div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"col-sm-3\">\r\n");
      out.write("                                    3\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"col-9\">\r\n");
      out.write("                                    <div class=\"card my-1\">9</div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"col-sm-2\">\r\n");
      out.write("                                    2\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"col-10\">\r\n");
      out.write("                                    <div class=\"card my-1\">10</div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"col-sm-1\">\r\n");
      out.write("                                    1\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"col-11\">\r\n");
      out.write("                                    <div class=\"card my-1\">11</div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </section>\r\n");
      out.write("\r\n");
      out.write("                        <section id=\"forms\" class=\"py-3\">\r\n");
      out.write("                            <div class=\"row\">\r\n");
      out.write("                                <div class=\"col-md-12\">\r\n");
      out.write("                                    <h4>Forms and Inputs</h4>\r\n");
      out.write("\r\n");
      out.write("                                    <!-- Form -->\r\n");
      out.write("                                    <form role=\"form\">\r\n");
      out.write("                                        <div class=\"form-group row\">\r\n");
      out.write("                                            <label class=\"col-md-2 col-form-label form-control-label text-muted\">First</label>\r\n");
      out.write("                                            <div class=\"col-md-4\">\r\n");
      out.write("                                                <input class=\"form-control\" type=\"text\" value=\"Jane\">\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <label class=\"col-md-1 col-form-label form-control-label text-muted\">Last</label>\r\n");
      out.write("                                            <div class=\"col-md-5\">\r\n");
      out.write("                                                <input class=\"form-control\" type=\"text\" value=\"Bishop\">\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"form-group row\">\r\n");
      out.write("                                            <label class=\"col-lg-2 col-form-label form-control-label text-muted\">Address</label>\r\n");
      out.write("                                            <div class=\"col-lg-10\">\r\n");
      out.write("                                                <input class=\"form-control\" type=\"text\" placeholder=\"Street\">\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"form-group row\">\r\n");
      out.write("                                            <label class=\"col-lg-2 col-form-label form-control-label text-muted\"></label>\r\n");
      out.write("                                            <div class=\"col-lg-6\">\r\n");
      out.write("                                                <input class=\"form-control\" type=\"text\" placeholder=\"City\">\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"col-lg-4\">\r\n");
      out.write("                                                <select class=\"form-control\">\r\n");
      out.write("                                                    <option>State</option>\r\n");
      out.write("                                                    <option>AK</option>\r\n");
      out.write("                                                    <option>AZ</option>\r\n");
      out.write("                                                    <option>CA</option>\r\n");
      out.write("                                                    <option>CO</option>\r\n");
      out.write("                                                </select>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"form-group row was-validated\">\r\n");
      out.write("                                            <label class=\"col-lg-2 col-form-label form-control-label text-muted\">Username</label>\r\n");
      out.write("                                            <div class=\"col-lg-10\">\r\n");
      out.write("                                                <input class=\"form-control\" type=\"text\" required=\"\">\r\n");
      out.write("                                                <div class=\"invalid-feedback\">\r\n");
      out.write("                                                    Username is required.\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"form-group row\">\r\n");
      out.write("                                            <label class=\"col-lg-2 col-form-label form-control-label text-muted\">Password</label>\r\n");
      out.write("                                            <div class=\"col-lg-10\">\r\n");
      out.write("                                                <input class=\"form-control\" type=\"password\" value=\"11111122333\">\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"form-group row\">\r\n");
      out.write("                                            <label class=\"col-lg-2 col-form-label form-control-label\"></label>\r\n");
      out.write("                                            <div class=\"col-lg-10\">\r\n");
      out.write("                                                <input type=\"reset\" class=\"btn btn-outline-secondary mr-2\" value=\"Cancel\">\r\n");
      out.write("                                                <input type=\"button\" class=\"btn btn-primary mr-2\" value=\"Submit\">\r\n");
      out.write("                                                <div class=\"custom-control custom-checkbox d-inline\">\r\n");
      out.write("                                                    <input type=\"checkbox\" class=\"custom-control-input\" id=\"customCheck\" checked=\"\">\r\n");
      out.write("                                                    <label class=\"custom-control-label\" for=\"customCheck\">Check me out</label>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </form>\r\n");
      out.write("\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </section>\r\n");
      out.write("\r\n");
      out.write("                        <section id=\"more\" class=\"py-2\">\r\n");
      out.write("                            <div class=\"row\">\r\n");
      out.write("                                <div class=\"col-md-12\">\r\n");
      out.write("                                    <div class=\"table-responsive\">\r\n");
      out.write("                                        <table class=\"table table-hover table-sm\">\r\n");
      out.write("                                            <tbody>\r\n");
      out.write("                                                <tr>\r\n");
      out.write("                                                    <th class=\"w-25\">Location</th>\r\n");
      out.write("                                                    <th class=\"w-50\">Date</th>\r\n");
      out.write("                                                    <th class=\"w-25\">Visits</th>\r\n");
      out.write("                                                </tr>\r\n");
      out.write("                                                <tr>\r\n");
      out.write("                                                    <td>Westfield</td>\r\n");
      out.write("                                                    <td>08.05.18 <span class=\"badge badge-primary\">badge</span></td>\r\n");
      out.write("                                                    <td>2323</td>\r\n");
      out.write("                                                </tr>\r\n");
      out.write("                                                <tr>\r\n");
      out.write("                                                    <td>Galway</td>\r\n");
      out.write("                                                    <td>08.05.18 <span class=\"badge badge-pill badge-primary\">badge-pill</span></td>\r\n");
      out.write("                                                    <td>5362</td>\r\n");
      out.write("                                                </tr>\r\n");
      out.write("                                                <tr class=\"table-primary\">\r\n");
      out.write("                                                    <td>Bern</td>\r\n");
      out.write("                                                    <td>08.05.18</td>\r\n");
      out.write("                                                    <td>153</td>\r\n");
      out.write("                                                </tr>\r\n");
      out.write("                                            </tbody>\r\n");
      out.write("                                        </table>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"w-100 my-4\"></div>\r\n");
      out.write("                                <div class=\"col-md-12\">\r\n");
      out.write("                                    <div class=\"progress mb-2\">\r\n");
      out.write("                                        <div class=\"progress-bar bg-primary w-25\" role=\"progressbar\" aria-valuenow=\"25\" aria-valuemin=\"0\" aria-valuemax=\"100\">25%</div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"col-md-12\">\r\n");
      out.write("\r\n");
      out.write("                                    <!-- Alert -->\r\n");
      out.write("                                    <div class=\"alert alert-primary alert-dismissable show fade\" role=\"alert\">\r\n");
      out.write("                                        <button type=\"button\" class=\"close\" data-dismiss=\"alert\" aria-label=\"Close\">\r\n");
      out.write("                                            <span aria-hidden=\"true\">×</span>\r\n");
      out.write("                                        </button>\r\n");
      out.write("                                        <strong>Well done!</strong> You successfully read this important alert message.\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </section>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
