/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.58
 * Generated at: 2020-10-07 06:07:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.try_;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class test_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset='utf-8' />\r\n");
      out.write("<link href='../packages/core/main.css' rel='stylesheet' />\r\n");
      out.write("<link href='../packages/daygrid/main.css' rel='stylesheet' />\r\n");
      out.write("<link href='../packages/timegrid/main.css' rel='stylesheet' />\r\n");
      out.write("<link href='../packages/list/main.css' rel='stylesheet' />\r\n");
      out.write("<script src='../packages/core/main.js'></script>\r\n");
      out.write("<script src='../packages/interaction/main.js'></script>\r\n");
      out.write("<script src='../packages/daygrid/main.js'></script>\r\n");
      out.write("<script src='../packages/timegrid/main.js'></script>\r\n");
      out.write("<script src='../packages/list/main.js'></script>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("  document.addEventListener('DOMContentLoaded', function() {\r\n");
      out.write("    var calendarEl = document.getElementById('calendar');\r\n");
      out.write("\r\n");
      out.write("    var calendar = new FullCalendar.Calendar(calendarEl, {\r\n");
      out.write("      plugins: [ 'interaction', 'dayGrid', 'timeGrid', 'list' ],\r\n");
      out.write("      height: 'parent',\r\n");
      out.write("      header: {\r\n");
      out.write("        left: 'prev,next today',\r\n");
      out.write("        center: 'title',\r\n");
      out.write("        right: 'dayGridMonth,timeGridWeek,timeGridDay,listWeek'\r\n");
      out.write("      },\r\n");
      out.write("      defaultView: 'dayGridMonth',\r\n");
      out.write("      defaultDate: '2020-02-12',\r\n");
      out.write("      navLinks: true, // can click day/week names to navigate views\r\n");
      out.write("      editable: true,\r\n");
      out.write("      eventLimit: true, // allow \"more\" link when too many events\r\n");
      out.write("      events: [\r\n");
      out.write("        {\r\n");
      out.write("          title: 'All Day Event',\r\n");
      out.write("          start: '2020-02-01',\r\n");
      out.write("        },\r\n");
      out.write("        {\r\n");
      out.write("          title: 'Long Event',\r\n");
      out.write("          start: '2020-02-07',\r\n");
      out.write("          end: '2020-02-10'\r\n");
      out.write("        },\r\n");
      out.write("        {\r\n");
      out.write("          groupId: 999,\r\n");
      out.write("          title: 'Repeating Event',\r\n");
      out.write("          start: '2020-02-09T16:00:00'\r\n");
      out.write("        },\r\n");
      out.write("        {\r\n");
      out.write("          groupId: 999,\r\n");
      out.write("          title: 'Repeating Event',\r\n");
      out.write("          start: '2020-02-16T16:00:00'\r\n");
      out.write("        },\r\n");
      out.write("        {\r\n");
      out.write("          title: 'Conference',\r\n");
      out.write("          start: '2020-02-11',\r\n");
      out.write("          end: '2020-02-13'\r\n");
      out.write("        },\r\n");
      out.write("        {\r\n");
      out.write("          title: 'Meeting',\r\n");
      out.write("          start: '2020-02-12T10:30:00',\r\n");
      out.write("          end: '2020-02-12T12:30:00'\r\n");
      out.write("        },\r\n");
      out.write("        {\r\n");
      out.write("          title: 'Lunch',\r\n");
      out.write("          start: '2020-02-12T12:00:00'\r\n");
      out.write("        },\r\n");
      out.write("        {\r\n");
      out.write("          title: 'Meeting',\r\n");
      out.write("          start: '2020-02-12T14:30:00'\r\n");
      out.write("        },\r\n");
      out.write("        {\r\n");
      out.write("          title: 'Happy Hour',\r\n");
      out.write("          start: '2020-02-12T17:30:00'\r\n");
      out.write("        },\r\n");
      out.write("        {\r\n");
      out.write("          title: 'Dinner',\r\n");
      out.write("          start: '2020-02-12T20:00:00'\r\n");
      out.write("        },\r\n");
      out.write("        {\r\n");
      out.write("          title: 'Birthday Party',\r\n");
      out.write("          start: '2020-02-13T07:00:00'\r\n");
      out.write("        },\r\n");
      out.write("        {\r\n");
      out.write("          title: 'Click for Google',\r\n");
      out.write("          url: 'http://google.com/',\r\n");
      out.write("          start: '2020-02-28'\r\n");
      out.write("        }\r\n");
      out.write("      ]\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    calendar.render();\r\n");
      out.write("  });\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("  html, body {\r\n");
      out.write("    overflow: hidden; /* don't do scrollbars */\r\n");
      out.write("    font-family: Arial, Helvetica Neue, Helvetica, sans-serif;\r\n");
      out.write("    font-size: 14px;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  #calendar-container {\r\n");
      out.write("    position: fixed;\r\n");
      out.write("    top: 0;\r\n");
      out.write("    left: 0;\r\n");
      out.write("    right: 0;\r\n");
      out.write("    bottom: 0;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  .fc-header-toolbar {\r\n");
      out.write("    /*\r\n");
      out.write("    the calendar will be butting up against the edges,\r\n");
      out.write("    but let's scoot in the header's buttons\r\n");
      out.write("    */\r\n");
      out.write("    padding-top: 1em;\r\n");
      out.write("    padding-left: 1em;\r\n");
      out.write("    padding-right: 1em;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("  <div id='calendar-container'>\r\n");
      out.write("    <div id='calendar'></div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
